sudo: required
services: 
  - docker

#build the image
  before_install:
    - docker build -f dockerFile.dev -t manan222/docker-react .
#test the image
  script:
    - docker run  manan222/docker-react npm run test -- -- covergae