sudo: required
services: 
  - docker

#build the image
  before_install:
    - docker build  -t manan222/docker-react -f dockerFile.dev .
#test the image
  script:
    - docker run -e CI=true  manan222/docker-react npm run test 